// Generated by `tests/codegen.rs`; edit the generator rather than this file

use std::borrow::Cow;

use super::{Attributes, Encode, GlobalAttributes, Text, Unescaped};

/// The `<html>` element
pub(crate) struct Html<'a> {
    attributes: Attributes<'a>,
    head: Head<'a>,
    body: Body<'a>,
}

impl<'a> Html<'a> {
    /// Creates the element with the given `head` and `body`
    pub(crate) fn new(head: impl Into<Head<'a>>, body: impl Into<Body<'a>>) -> Self {
        Self {
            attributes: Attributes::default(),
            head: head.into(),
            body: body.into(),
        }
    }

    /// Sets the `lang` attribute
    pub(crate) fn lang(mut self, value: impl Into<Cow<'a, str>>) -> Self {
        self.attributes.set("lang", value.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Html<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Html<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<html");
        self.attributes.encode(out);
        out.push('>');
        self.head.encode(out);
        self.body.encode(out);
        out.push_str("</html>");
    }
}

/// The `<head>` element
pub(crate) struct Head<'a> {
    attributes: Attributes<'a>,
    children: Vec<MetadataContent<'a>>,
    title: Title<'a>,
}

impl<'a> Head<'a> {
    /// Creates the element with the given `title`
    pub(crate) fn new(title: impl Into<Title<'a>>) -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
            title: title.into(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<MetadataContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Head<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Head<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<head");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        self.title.encode(out);
        out.push_str("</head>");
    }
}

/// The `<title>` element
pub(crate) struct Title<'a> {
    attributes: Attributes<'a>,
    text: Text<'a>,
}

impl<'a> Title<'a> {
    /// Creates the element with the given `text`
    pub(crate) fn new(text: impl Into<Text<'a>>) -> Self {
        Self {
            attributes: Attributes::default(),
            text: text.into(),
        }
    }
}

impl<'a> GlobalAttributes<'a> for Title<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Title<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<title");
        self.attributes.encode(out);
        out.push('>');
        self.text.encode(out);
        out.push_str("</title>");
    }
}

/// The `<meta>` element
pub(crate) struct Meta<'a> {
    attributes: Attributes<'a>,
}

impl<'a> Meta<'a> {
    /// Creates the element with the given `charset`
    pub(crate) fn charset(charset: impl Into<Cow<'a, str>>) -> Self {
        let mut attributes = Attributes::default();
        attributes.set("charset", charset.into());
        Self { attributes }
    }

    /// Creates the element with the given `name` and `content`
    pub(crate) fn name(name: impl Into<Cow<'a, str>>, content: impl Into<Cow<'a, str>>) -> Self {
        let mut attributes = Attributes::default();
        attributes.set("name", name.into());
        attributes.set("content", content.into());
        Self { attributes }
    }
}

impl<'a> GlobalAttributes<'a> for Meta<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Meta<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<meta");
        self.attributes.encode(out);
        out.push('>');
    }
}

/// The `<link>` element
pub(crate) struct Link<'a> {
    attributes: Attributes<'a>,
}

impl<'a> Link<'a> {
    /// Creates the element with the given `rel` and `href`
    pub(crate) fn new(rel: impl Into<Cow<'a, str>>, href: impl Into<Cow<'a, str>>) -> Self {
        let mut attributes = Attributes::default();
        attributes.set("rel", rel.into());
        attributes.set("href", href.into());
        Self { attributes }
    }
}

impl<'a> GlobalAttributes<'a> for Link<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Link<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<link");
        self.attributes.encode(out);
        out.push('>');
    }
}

/// The `<body>` element
pub(crate) struct Body<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Body<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Body<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Body<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<body");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</body>");
    }
}

/// The `<nav>` element
pub(crate) struct Nav<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Nav<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Nav<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Nav<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<nav");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</nav>");
    }
}

/// The `<main>` element
pub(crate) struct Main<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Main<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Main<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Main<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<main");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</main>");
    }
}

/// The `<section>` element
pub(crate) struct Section<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Section<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Section<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Section<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<section");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</section>");
    }
}

/// The `<article>` element
pub(crate) struct Article<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Article<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Article<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Article<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<article");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</article>");
    }
}

/// The `<header>` element
pub(crate) struct Header<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Header<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Header<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Header<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<header");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</header>");
    }
}

/// The `<div>` element
pub(crate) struct Div<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Div<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Div<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Div<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<div");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</div>");
    }
}

/// The `<span>` element
pub(crate) struct Span<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> Span<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Span<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Span<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<span");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</span>");
    }
}

/// The `<h1>` element
pub(crate) struct H1<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> H1<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for H1<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for H1<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<h1");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</h1>");
    }
}

/// The `<h2>` element
pub(crate) struct H2<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> H2<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for H2<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for H2<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<h2");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</h2>");
    }
}

/// The `<p>` element
pub(crate) struct P<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> P<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for P<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for P<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<p");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</p>");
    }
}

/// The `<ul>` element
pub(crate) struct Ul<'a> {
    attributes: Attributes<'a>,
    children: Vec<Li<'a>>,
}

impl<'a> Ul<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<Li<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Ul<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Ul<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<ul");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</ul>");
    }
}

/// The `<li>` element
pub(crate) struct Li<'a> {
    attributes: Attributes<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Li<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Li<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Li<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<li");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</li>");
    }
}

/// The `<a>` element
pub(crate) struct A<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> A<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }

    /// Sets the `href` attribute
    pub(crate) fn href(mut self, value: impl Into<Cow<'a, str>>) -> Self {
        self.attributes.set("href", value.into());
        self
    }

    /// Sets the `aria-current` attribute
    pub(crate) fn aria_current(mut self, value: impl Into<Cow<'a, str>>) -> Self {
        self.attributes.set("aria-current", value.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for A<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for A<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<a");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</a>");
    }
}

/// The `<strong>` element
pub(crate) struct Strong<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> Strong<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Strong<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Strong<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<strong");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</strong>");
    }
}

/// The `<time>` element
pub(crate) struct Time<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> Time<'a> {
    /// Creates the element with the given `datetime`
    pub(crate) fn new(datetime: impl Into<Cow<'a, str>>) -> Self {
        let mut attributes = Attributes::default();
        attributes.set("datetime", datetime.into());
        Self {
            attributes,
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Time<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Time<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<time");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</time>");
    }
}

/// The `<details>` element
pub(crate) struct Details<'a> {
    attributes: Attributes<'a>,
    summary: Summary<'a>,
    children: Vec<FlowContent<'a>>,
}

impl<'a> Details<'a> {
    /// Creates the element with the given `summary`
    pub(crate) fn new(summary: impl Into<Summary<'a>>) -> Self {
        Self {
            attributes: Attributes::default(),
            summary: summary.into(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<FlowContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }

    /// Sets the `open` attribute
    pub(crate) fn open(mut self) -> Self {
        self.attributes.set_flag("open");
        self
    }
}

impl<'a> GlobalAttributes<'a> for Details<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Details<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<details");
        self.attributes.encode(out);
        out.push('>');
        self.summary.encode(out);
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</details>");
    }
}

/// The `<summary>` element
pub(crate) struct Summary<'a> {
    attributes: Attributes<'a>,
    children: Vec<PhrasingContent<'a>>,
}

impl<'a> Summary<'a> {
    /// Creates the element without children
    pub(crate) fn new() -> Self {
        Self {
            attributes: Attributes::default(),
            children: Vec::new(),
        }
    }

    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<PhrasingContent<'a>>) -> Self {
        self.children.push(child.into());
        self
    }
}

impl<'a> GlobalAttributes<'a> for Summary<'a> {
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {
        &mut self.attributes
    }
}

impl Encode for Summary<'_> {
    fn encode(&self, out: &mut String) {
        out.push_str("<summary");
        self.attributes.encode(out);
        out.push('>');
        for child in &self.children {
            child.encode(out);
        }
        out.push_str("</summary>");
    }
}

/// Metadata content, which sets up the presentation or behavior of the document
pub(crate) enum MetadataContent<'a> {
    Link(Link<'a>),
    Meta(Meta<'a>),
}

impl Encode for MetadataContent<'_> {
    fn encode(&self, out: &mut String) {
        match self {
            Self::Link(inner) => inner.encode(out),
            Self::Meta(inner) => inner.encode(out),
        }
    }
}

impl<'a> From<Link<'a>> for MetadataContent<'a> {
    fn from(value: Link<'a>) -> Self {
        Self::Link(value)
    }
}

impl<'a> From<Meta<'a>> for MetadataContent<'a> {
    fn from(value: Meta<'a>) -> Self {
        Self::Meta(value)
    }
}

/// Flow content, which makes up the body of the document
pub(crate) enum FlowContent<'a> {
    A(A<'a>),
    Article(Article<'a>),
    Details(Details<'a>),
    Div(Div<'a>),
    H1(H1<'a>),
    H2(H2<'a>),
    Header(Header<'a>),
    Main(Main<'a>),
    Nav(Nav<'a>),
    P(P<'a>),
    Section(Section<'a>),
    Span(Span<'a>),
    Strong(Strong<'a>),
    Text(Text<'a>),
    Time(Time<'a>),
    Ul(Ul<'a>),
    Unescaped(Unescaped<'a>),
}

impl Encode for FlowContent<'_> {
    fn encode(&self, out: &mut String) {
        match self {
            Self::A(inner) => inner.encode(out),
            Self::Article(inner) => inner.encode(out),
            Self::Details(inner) => inner.encode(out),
            Self::Div(inner) => inner.encode(out),
            Self::H1(inner) => inner.encode(out),
            Self::H2(inner) => inner.encode(out),
            Self::Header(inner) => inner.encode(out),
            Self::Main(inner) => inner.encode(out),
            Self::Nav(inner) => inner.encode(out),
            Self::P(inner) => inner.encode(out),
            Self::Section(inner) => inner.encode(out),
            Self::Span(inner) => inner.encode(out),
            Self::Strong(inner) => inner.encode(out),
            Self::Text(inner) => inner.encode(out),
            Self::Time(inner) => inner.encode(out),
            Self::Ul(inner) => inner.encode(out),
            Self::Unescaped(inner) => inner.encode(out),
        }
    }
}

impl<'a> From<A<'a>> for FlowContent<'a> {
    fn from(value: A<'a>) -> Self {
        Self::A(value)
    }
}

impl<'a> From<Article<'a>> for FlowContent<'a> {
    fn from(value: Article<'a>) -> Self {
        Self::Article(value)
    }
}

impl<'a> From<Details<'a>> for FlowContent<'a> {
    fn from(value: Details<'a>) -> Self {
        Self::Details(value)
    }
}

impl<'a> From<Div<'a>> for FlowContent<'a> {
    fn from(value: Div<'a>) -> Self {
        Self::Div(value)
    }
}

impl<'a> From<H1<'a>> for FlowContent<'a> {
    fn from(value: H1<'a>) -> Self {
        Self::H1(value)
    }
}

impl<'a> From<H2<'a>> for FlowContent<'a> {
    fn from(value: H2<'a>) -> Self {
        Self::H2(value)
    }
}

impl<'a> From<Header<'a>> for FlowContent<'a> {
    fn from(value: Header<'a>) -> Self {
        Self::Header(value)
    }
}

impl<'a> From<Main<'a>> for FlowContent<'a> {
    fn from(value: Main<'a>) -> Self {
        Self::Main(value)
    }
}

impl<'a> From<Nav<'a>> for FlowContent<'a> {
    fn from(value: Nav<'a>) -> Self {
        Self::Nav(value)
    }
}

impl<'a> From<P<'a>> for FlowContent<'a> {
    fn from(value: P<'a>) -> Self {
        Self::P(value)
    }
}

impl<'a> From<Section<'a>> for FlowContent<'a> {
    fn from(value: Section<'a>) -> Self {
        Self::Section(value)
    }
}

impl<'a> From<Span<'a>> for FlowContent<'a> {
    fn from(value: Span<'a>) -> Self {
        Self::Span(value)
    }
}

impl<'a> From<Strong<'a>> for FlowContent<'a> {
    fn from(value: Strong<'a>) -> Self {
        Self::Strong(value)
    }
}

impl<'a> From<Text<'a>> for FlowContent<'a> {
    fn from(value: Text<'a>) -> Self {
        Self::Text(value)
    }
}

impl<'a> From<Time<'a>> for FlowContent<'a> {
    fn from(value: Time<'a>) -> Self {
        Self::Time(value)
    }
}

impl<'a> From<Ul<'a>> for FlowContent<'a> {
    fn from(value: Ul<'a>) -> Self {
        Self::Ul(value)
    }
}

impl<'a> From<Unescaped<'a>> for FlowContent<'a> {
    fn from(value: Unescaped<'a>) -> Self {
        Self::Unescaped(value)
    }
}

impl<'a> From<&'a str> for FlowContent<'a> {
    fn from(text: &'a str) -> Self {
        Self::Text(text.into())
    }
}

impl<'a> From<&'a String> for FlowContent<'a> {
    fn from(text: &'a String) -> Self {
        Self::Text(text.into())
    }
}

impl<'a> From<String> for FlowContent<'a> {
    fn from(text: String) -> Self {
        Self::Text(text.into())
    }
}

impl<'a> From<Cow<'a, str>> for FlowContent<'a> {
    fn from(text: Cow<'a, str>) -> Self {
        Self::Text(text.into())
    }
}

/// Phrasing content, which is text and the elements that mark it up within a paragraph
pub(crate) enum PhrasingContent<'a> {
    A(A<'a>),
    Span(Span<'a>),
    Strong(Strong<'a>),
    Text(Text<'a>),
    Time(Time<'a>),
}

impl Encode for PhrasingContent<'_> {
    fn encode(&self, out: &mut String) {
        match self {
            Self::A(inner) => inner.encode(out),
            Self::Span(inner) => inner.encode(out),
            Self::Strong(inner) => inner.encode(out),
            Self::Text(inner) => inner.encode(out),
            Self::Time(inner) => inner.encode(out),
        }
    }
}

impl<'a> From<A<'a>> for PhrasingContent<'a> {
    fn from(value: A<'a>) -> Self {
        Self::A(value)
    }
}

impl<'a> From<Span<'a>> for PhrasingContent<'a> {
    fn from(value: Span<'a>) -> Self {
        Self::Span(value)
    }
}

impl<'a> From<Strong<'a>> for PhrasingContent<'a> {
    fn from(value: Strong<'a>) -> Self {
        Self::Strong(value)
    }
}

impl<'a> From<Text<'a>> for PhrasingContent<'a> {
    fn from(value: Text<'a>) -> Self {
        Self::Text(value)
    }
}

impl<'a> From<Time<'a>> for PhrasingContent<'a> {
    fn from(value: Time<'a>) -> Self {
        Self::Time(value)
    }
}

impl<'a> From<&'a str> for PhrasingContent<'a> {
    fn from(text: &'a str) -> Self {
        Self::Text(text.into())
    }
}

impl<'a> From<&'a String> for PhrasingContent<'a> {
    fn from(text: &'a String) -> Self {
        Self::Text(text.into())
    }
}

impl<'a> From<String> for PhrasingContent<'a> {
    fn from(text: String) -> Self {
        Self::Text(text.into())
    }
}

impl<'a> From<Cow<'a, str>> for PhrasingContent<'a> {
    fn from(text: Cow<'a, str>) -> Self {
        Self::Text(text.into())
    }
}
