[workspace]
members = ["mail","store","util","web"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
ammonia = "4.2.1"
axum = "0.8.9"
base64 = "0.23.1"
clap = { version = "4.6.7", features = ["derive", "env"] }
eyre = "0.6"
getrandom = "0.4.3"
imap-proto = "0.17.0"
indicatif = "0.18.6"
jiff = "0.2.38"
mail-parser = "0.11.9"
nom = "8"
percent-encoding = "2.3.2"
redb = "4.3.0"
reqwest = { version = "0.13.5", default-features = false, features = ["form", "json", "rustls"] }
rustls-platform-verifier = "0.7.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
sha2 = "0.11.0"
similar-asserts = "2.0.0"
tempfile = "3.27.0"
thiserror = "2.0.21"
tokio = { version = "1.53.2", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-rustls = "0.26.6"
tower = { version = "0.5.3", features = ["util"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
trivial_numeric_casts = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage,coverage_nightly)"] }
unnameable_types = "warn"
unreachable_pub = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
alloc_instead_of_core = "warn"
cloned_instead_of_copied = "warn"
manual_let_else = "warn"
or_fun_call = "warn"
std_instead_of_core = "warn"
undocumented_unsafe_blocks = "warn"
upper_case_acronyms = "warn"
use_self = "warn"
