//! Generates `src/html/generated.rs`
//!
//! If the checked-in file differs from the generated code, the test writes the new contents and
//! fails, so that a second run passes.
//!
//! The children of each element follow its content model: a child that must be present exactly
//! once is a field, which the constructor takes as an argument, while children that can be present
//! any number of times are added with `child()`. These are usually a content category like flow
//! content, which is generated as an enum with a variant for each element in the category.
//! Restrictions on descendants, like `<a>` not containing other interactive content, are not
//! represented.

use core::fmt::{self, Write};
use std::fs;

use Content::{Many, One};

#[test]
fn html() -> Result<(), Box<dyn core::error::Error>> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/src/html/generated.rs");
    let old = fs::read_to_string(path)?;

    let mut new = String::from(
        "// Generated by `tests/codegen.rs`; edit the generator rather than this file

use std::borrow::Cow;

use super::{Attributes, Encode, GlobalAttributes, Text, Unescaped};
",
    );

    for element in ELEMENTS {
        element.write(&mut new)?;
    }

    for category in CATEGORIES {
        category.write(&mut new)?;
    }

    if old != new {
        fs::write(path, &new)?;
    }

    similar_asserts::assert_eq!(old, new);
    Ok(())
}

const ELEMENTS: &[Element] = &[
    Element::new("html")
        .content(&[One("Head"), One("Body")])
        .attributes(&["lang"]),
    // The title follows the other metadata, so that a long title can't push the character encoding
    // declaration out of the first 1024 bytes of the document.
    Element::new("head").content(&[Many(METADATA.name), One("Title")]),
    // The title is metadata content, but it is left out of the category because the `<head>` has
    // a field for it.
    Element::new("title").content(&[One("Text")]),
    Element::void("meta")
        .categories(&[METADATA])
        .constructors(&[
            Constructor {
                name: "charset",
                attributes: &["charset"],
            },
            Constructor {
                name: "name",
                attributes: &["name", "content"],
            },
        ]),
    Element::void("link")
        .categories(&[METADATA])
        .constructors(&[Constructor {
            name: "new",
            attributes: &["rel", "href"],
        }]),
    Element::new("body").content(&[Many(FLOW.name)]),
    Element::new("nav")
        .categories(&[FLOW])
        .content(&[Many(FLOW.name)]),
    Element::new("main")
        .categories(&[FLOW])
        .content(&[Many(FLOW.name)]),
    Element::new("section")
        .categories(&[FLOW])
        .content(&[Many(FLOW.name)]),
    Element::new("article")
        .categories(&[FLOW])
        .content(&[Many(FLOW.name)]),
    Element::new("header")
        .categories(&[FLOW])
        .content(&[Many(FLOW.name)]),
    Element::new("div")
        .categories(&[FLOW])
        .content(&[Many(FLOW.name)]),
    Element::new("span")
        .categories(&[FLOW, PHRASING])
        .content(&[Many(PHRASING.name)]),
    Element::new("h1")
        .categories(&[FLOW])
        .content(&[Many(PHRASING.name)]),
    Element::new("h2")
        .categories(&[FLOW])
        .content(&[Many(PHRASING.name)]),
    Element::new("p")
        .categories(&[FLOW])
        .content(&[Many(PHRASING.name)]),
    Element::new("ul")
        .categories(&[FLOW])
        .content(&[Many("Li")]),
    Element::new("li").content(&[Many(FLOW.name)]),
    Element::new("a")
        .categories(&[FLOW, PHRASING])
        .content(&[Many(PHRASING.name)])
        .attributes(&["href", "aria-current"]),
    Element::new("strong")
        .categories(&[FLOW, PHRASING])
        .content(&[Many(PHRASING.name)]),
    // Without a `datetime` attribute, the content must be a valid date or time
    Element::new("time")
        .categories(&[FLOW, PHRASING])
        .content(&[Many(PHRASING.name)])
        .constructors(&[Constructor {
            name: "new",
            attributes: &["datetime"],
        }]),
    Element::new("details")
        .categories(&[FLOW])
        .content(&[One("Summary"), Many(FLOW.name)])
        .flags(&["open"]),
    Element::new("summary").content(&[Many(PHRASING.name)]),
];

const CATEGORIES: &[Category] = &[METADATA, FLOW, PHRASING];

const METADATA: Category = Category {
    name: "MetadataContent",
    doc: "Metadata content, which sets up the presentation or behavior of the document",
    other: &[],
};

const FLOW: Category = Category {
    name: "FlowContent",
    doc: "Flow content, which makes up the body of the document",
    other: &["Text", "Unescaped"],
};

const PHRASING: Category = Category {
    name: "PhrasingContent",
    doc: "Phrasing content, which is text and the elements that mark it up within a paragraph",
    other: &["Text"],
};

/// An HTML element to generate a type for
struct Element {
    /// The tag name, which is also the type name in title case
    tag: &'static str,
    /// Whether the element is a void element, which has no children or end tag
    void: bool,
    /// The content categories the element belongs to
    categories: &'static [Category],
    /// The children of the element, in the order in which they are encoded
    content: &'static [Content],
    /// The constructors of the type
    constructors: &'static [Constructor],
    /// Optional attributes that take a value
    attributes: &'static [&'static str],
    /// Boolean attributes, which are either present or absent
    flags: &'static [&'static str],
}

impl Element {
    const fn new(tag: &'static str) -> Self {
        Self {
            tag,
            void: false,
            categories: &[],
            content: &[],
            constructors: &[Constructor {
                name: "new",
                attributes: &[],
            }],
            attributes: &[],
            flags: &[],
        }
    }

    const fn void(tag: &'static str) -> Self {
        Self {
            void: true,
            ..Self::new(tag)
        }
    }

    const fn categories(self, categories: &'static [Category]) -> Self {
        Self { categories, ..self }
    }

    const fn content(self, content: &'static [Content]) -> Self {
        Self { content, ..self }
    }

    const fn constructors(self, constructors: &'static [Constructor]) -> Self {
        Self {
            constructors,
            ..self
        }
    }

    const fn attributes(self, attributes: &'static [&'static str]) -> Self {
        Self { attributes, ..self }
    }

    const fn flags(self, flags: &'static [&'static str]) -> Self {
        Self { flags, ..self }
    }

    fn write(&self, out: &mut String) -> fmt::Result {
        let Self {
            tag,
            void,
            categories: _,
            content,
            constructors,
            attributes,
            flags,
        } = self;

        let name = self.name();
        write!(
            out,
            "
/// The `<{tag}>` element
pub(crate) struct {name}<'a> {{
    attributes: Attributes<'a>,
"
        )?;

        for part in *content {
            match part {
                One(ty) => writeln!(out, "    {}: {ty}<'a>,", field(ty))?,
                Many(ty) => writeln!(out, "    children: Vec<{ty}<'a>>,")?,
            }
        }

        let mut methods = Vec::new();
        for constructor in *constructors {
            methods.push(constructor.method(content));
        }

        for part in *content {
            let Many(ty) = part else { continue };
            methods.push(format!(
                "    /// Appends a child
    pub(crate) fn child(mut self, child: impl Into<{ty}<'a>>) -> Self {{
        self.children.push(child.into());
        self
    }}
"
            ));
        }

        for attribute in *attributes {
            let method = attribute.replace('-', "_");
            methods.push(format!(
                "    /// Sets the `{attribute}` attribute
    pub(crate) fn {method}(mut self, value: impl Into<Cow<'a, str>>) -> Self {{
        self.attributes.set(\"{attribute}\", value.into());
        self
    }}
"
            ));
        }

        for flag in *flags {
            methods.push(format!(
                "    /// Sets the `{flag}` attribute
    pub(crate) fn {flag}(mut self) -> Self {{
        self.attributes.set_flag(\"{flag}\");
        self
    }}
"
            ));
        }

        write!(
            out,
            "}}

impl<'a> {name}<'a> {{
{}}}

impl<'a> GlobalAttributes<'a> for {name}<'a> {{
    fn attributes_mut(&mut self) -> &mut Attributes<'a> {{
        &mut self.attributes
    }}
}}

impl Encode for {name}<'_> {{
    fn encode(&self, out: &mut String) {{
        out.push_str(\"<{tag}\");
        self.attributes.encode(out);
        out.push('>');
",
            methods.join("\n")
        )?;

        for part in *content {
            match part {
                One(ty) => writeln!(out, "        self.{}.encode(out);", field(ty))?,
                Many(_) => out.push_str(
                    "        for child in &self.children {
            child.encode(out);
        }
",
                ),
            }
        }

        if !void {
            writeln!(out, "        out.push_str(\"</{tag}>\");")?;
        }

        out.push_str("    }\n}\n");
        Ok(())
    }

    fn name(&self) -> String {
        let mut name = self.tag[..1].to_ascii_uppercase();
        name.push_str(&self.tag[1..]);
        name
    }
}

/// A content category, which is generated as an enum with a variant for each of its members
struct Category {
    /// The name of the enum
    name: &'static str,
    /// The first line of the enum's documentation
    doc: &'static str,
    /// Members of the category that are not generated elements
    other: &'static [&'static str],
}

impl Category {
    fn write(&self, out: &mut String) -> fmt::Result {
        let Self { name, doc, other } = self;

        let mut members = ELEMENTS
            .iter()
            .filter(|element| element.categories.iter().any(|c| c.name == *name))
            .map(Element::name)
            .collect::<Vec<_>>();
        members.extend(other.iter().map(|ty| ty.to_string()));
        members.sort();

        write!(out, "\n/// {doc}\npub(crate) enum {name}<'a> {{\n")?;
        for member in &members {
            writeln!(out, "    {member}({member}<'a>),")?;
        }

        write!(
            out,
            "}}

impl Encode for {name}<'_> {{
    fn encode(&self, out: &mut String) {{
        match self {{
"
        )?;

        for member in &members {
            writeln!(
                out,
                "            Self::{member}(inner) => inner.encode(out),"
            )?;
        }

        out.push_str("        }\n    }\n}\n");
        for member in &members {
            write!(
                out,
                "
impl<'a> From<{member}<'a>> for {name}<'a> {{
    fn from(value: {member}<'a>) -> Self {{
        Self::{member}(value)
    }}
}}
"
            )?;
        }

        if !other.contains(&"Text") {
            return Ok(());
        }

        for ty in ["&'a str", "&'a String", "String", "Cow<'a, str>"] {
            write!(
                out,
                "
impl<'a> From<{ty}> for {name}<'a> {{
    fn from(text: {ty}) -> Self {{
        Self::Text(text.into())
    }}
}}
"
            )?;
        }

        Ok(())
    }
}

/// The children an element can have at some position in its content
enum Content {
    /// Exactly one child of the given type, stored in a field named after the type
    One(&'static str),
    /// Any number of children of the given type, stored in a `children` field
    Many(&'static str),
}

/// A constructor, which takes the required children and attributes as arguments
struct Constructor {
    /// The name of the constructor
    name: &'static str,
    /// The attributes that must be set
    attributes: &'static [&'static str],
}

impl Constructor {
    fn method(&self, content: &[Content]) -> String {
        let Self { name, attributes } = self;

        let mut arguments = Vec::new();
        let mut parameters = Vec::new();
        for attribute in *attributes {
            let argument = attribute.replace('-', "_");
            parameters.push(format!("{argument}: impl Into<Cow<'a, str>>"));
            arguments.push(argument);
        }

        for part in content {
            let One(ty) = part else { continue };
            let argument = field(ty);
            parameters.push(format!("{argument}: impl Into<{ty}<'a>>"));
            arguments.push(argument);
        }

        let doc = match arguments.as_slice() {
            [] => "Creates the element without children".to_owned(),
            [one] => format!("Creates the element with the given `{one}`"),
            [init @ .., last] => format!(
                "Creates the element with the given `{}` and `{last}`",
                init.join("`, `")
            ),
        };

        let mut signature = format!(
            "    pub(crate) fn {name}({}) -> Self {{",
            parameters.join(", ")
        );
        if signature.len() > 100 {
            signature = format!("    pub(crate) fn {name}(\n");
            for parameter in &parameters {
                writeln!(signature, "        {parameter},").unwrap();
            }
            signature.push_str("    ) -> Self {");
        }

        let mut method = format!("    /// {doc}\n{signature}\n");
        let mut fields = Vec::new();
        match attributes.is_empty() {
            true => fields.push("attributes: Attributes::default()".to_owned()),
            false => {
                method.push_str("        let mut attributes = Attributes::default();\n");
                for attribute in *attributes {
                    let argument = attribute.replace('-', "_");
                    writeln!(
                        method,
                        "        attributes.set(\"{attribute}\", {argument}.into());"
                    )
                    .unwrap();
                }
                fields.push("attributes".to_owned());
            }
        }

        for part in content {
            fields.push(match part {
                One(ty) => format!("{0}: {0}.into()", field(ty)),
                Many(_) => "children: Vec::new()".to_owned(),
            });
        }

        match fields.as_slice() {
            [only] if only == "attributes" => method.push_str("        Self { attributes }\n"),
            _ => {
                method.push_str("        Self {\n");
                for field in fields {
                    writeln!(method, "            {field},").unwrap();
                }
                method.push_str("        }\n");
            }
        }

        method.push_str("    }\n");
        method
    }
}

/// Returns the name of the field that stores a child of the given type
fn field(ty: &str) -> String {
    ty.to_ascii_lowercase()
}
