[package]
name = "encove-mail"
version = "0.1.0"
edition.workspace = true

[dependencies]
base64 = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
imap-proto = { workspace = true }
indicatif = { workspace = true }
jiff = { workspace = true }
mail-parser = { workspace = true }
nom = { workspace = true }
redb = { workspace = true }
rustls-platform-verifier = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
store = { package = "encove-store", path = "../store" }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
fixtures = ["dep:tempfile"]

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
